### ISSUE TITLE
Document how scripts can guard against older hubot versions

### ISSUE THREAD

**Issue by technicalpickles** [hubotio/hubot#1062]
Since hubot [2.13.0](https://github.com/github/hubot/blob/master/CHANGELOG.md#v2130) hubot has support for [listener metadata](https://hubot.github.com/docs/scripting/#listener-metadata), and [2.14.0](https://github.com/github/hubot/blob/master/CHANGELOG.md#v2140) introduced a way to use it: middleware. The problem is the function signature for `respond`, `hear`, etc has changed.

It's backwards compatible, in that an newer hubot loading a script without metadata work as expected. The problem is when you try to load an newer script into an older hubot: it expects the second parameter to be a function, and now it is a Object with keys/values, so it will probably fail with `Object isnt a function` or similar.

My first thought is to scripts have a peerDependency on hubot for >= 2.13.0 while still being 2.x, but I'm not sure how to specify that yet. There is also some weird stuff aroudn peerDependency where it might not always get installed.

Another thought is checking for hubot's version in the script, but this isn't exposed anywhere currently to a script.

The best bet I can think of is to do some feature sniffing to check for the behavior you want. In this case, it's checking `robot.respond.length`. If it's 3, then you should be okay since it has 3 parameters.  I think this should cause initializing to fail, because it means you are trying to load a script that's not supported. If you continue despite that, then there's scripts that won't work and users expect to. If a command isn't registered, it'd be unclear if it's because it's not working or if it's not even enabled.

cc  https://github.com/hubot-scripts/hubot-diagnostics/pull/1 https://github.com/hubot-scripts/hubot-pager-me/pull/54

**Comment by therealklanni** [comment]
It's a tricky issue, because it's caught in this grey area where we want to provide useful feature enhancements while at the same time providing backwards compatibility. While I understand the desire for backwards compatibility (especially since many scripts are poorly maintained), when does it make sense to drop backwards compatibility as a tradeoff for significant improvements? I'm not necessarily advocating for dropping backwards compatibility, though.

**Comment by therealklanni** [comment]
As a side note to this, I am excited about the middleware feature (still have yet to experiment with it), because I've been wanting this for some time for scripts like "hubot-admin" which can potentially be used to limit access to certain commands by way of not continuing the middleware chain to the would-be recipient middleware for the given command. Anyway, just sort of thinking aloud here :)

**Comment by therealklanni** [comment]
I'm also hesitant about the `peerDependency` requirement, because it's not very reliable. 

Hmmm. I haven't put much thought into it yet, but would default parameter values be a possible solution to the `Object is not a function` problem? I would have to review that part of the source to see if this would be viable, but just an initial thought.

**Comment by technicalpickles** [comment]
@gr2m this one may be relevant to https://github.com/hubotio/hubot/issues/1057
