### ISSUE TITLE
Port hubot from coffeescript to plain Javascipt (ES2015)

### ISSUE THREAD

**Issue by gasolin** [hubotio/hubot#1138]
.coffee does not look familiar for JS developers. 
After es6 is on the table and its easy to make es6 work on modern JS runtime through babel. Developers will have less motivation to learn .coffee and might cause maintenance issue in long term.

We almost complete the porting from hubot coffeescript to es6 (through babel)
including all .coffee and test cases. CI test passed and even passed eslint style check.
All hubot plugins are still workable.

Since the code looks different now, I setup a separate repo:
https://github.com/gasolin/webbybot

@technicalpickles would you consider move hubot to es6 based?

**Comment by gasolin** [comment]
We almost complete the porting . hubot-generated project just need minor change to use this es6 version. (mainly because I take different naming from hubot to better test the port result and avoid the confusion)

https://github.com/gasolin/webbybot#how-to-replace-hubot-to-webbybot

Still wait for feedback if hubot interesting in moving to es6 based.

**Comment by gasolin** [comment]
Hi, @technicalpickles , do you like Javascipt version, or I should fork from the Hubot?

**Comment by gasolin** [comment]
Wrote an article to explain the changes from Coffeescript to ES6 http://blog.gasolin.idv.tw/2016/03/how-we-ported-hubot-from-coffeescript.html

**Comment by technicalpickles** [comment]
I'd consider moving to ES6, but I'd be worried about it be effectively a rewrite. If there's a way to change individual files over one at a time, that'd be a lot lower risk. The biggest consideration I have is that it continues to work for existing hubot users.

**Comment by gasolin** [comment]
It's totally possible to change individual files over one at a time (that's what we did when porting hubot), hubot providing 77% test coverage, the ported result does fully compatible with current version, all plugins are still working.

I've created yeoman-generator-equivalent template to triage some edge cases, it works well
https://github.com/gasolin/webby_template

If that sounds good, I could start sending some patch to introduce the ES6 (babel) build script and change individual file one by one.

**Comment by enapupe** [comment]
@gasolin I'd like to thank you for your effort. You really have a point here. I came to github just to find an issue about this subject (my actual google query was `hubot fork es6`).
I have no interest in coffescript and that is frustrating.. hubot would definitely be 10x more exciting if it was ES6..
Thanks for putting so much time into something like that, I hope it merges with github interests, it would be a big win for everyone.

**Comment by rqc** [comment]
Hello, what would be the resolution on this? @technicalpickles would like a manual port and it seems to have been done by @gasolin. Are there any other roadblocks to accept a pull request from @gasolin? My organization is very interested in giving back to Hubot, but we are more inclined to use javascript (`es5` or `es6`) rather than `coffeescript` which doesn't seem to be that useful anymore.

**Comment by hpurmann** [comment]
I'd live with CoffeeScript for now if it would at least be _published_ as JS (like any other CoffeeScript module is). This is holding us back from using the hubot-test-helper (https://github.com/mtsmfm/hubot-test-helper/issues/33)

**Comment by gasolin** [comment]
@hpurmann moving to es6 doesn't mean you can't run coffeescript module anymore ([https://github.com/gasolin/webby_template the prototype] shows its totally possible). 
And this port is not happended in hubot codebase yet, so its an unrelated issue.

**Comment by hpurmann** [comment]
No, you got me wrong. Usually, modules written in CoffeeScript are transpiled to JavaScript as a `prepublish` step. This makes them usable for every other JavaScript project.

`hubot` has taken another approach and publishes the raw CoffeeScript source files which you obviously can't require in a pure JS context. This makes requiring of `hubot` only possible with CoffeeScript transpiling in place. @technicalpickles, can you elaborate on the reasoning behind this?

**Comment by halkeye** [comment]
Decaffeinate actually works really well in coverting coffeescript to es6

As much as I like it I'm not sure why it matters of the core is coffeescript or not. I write all my modules using es6 and have an index.js that calls robot.loadFile

Do you need to actually require hubot directly in your modules? I'm guessing maybe adapters?

**Comment by alangpierce** [comment]
Hi, I'm the main person working on the decaffeinate project recently, and I've been using hubot as one of the test cases. I have a fork of hubot that gets updated daily with the latest decaffeinate result:
https://github.com/decaffeinate-examples/hubot

It was generated completely automatically from this repo, and it's almost 100% JavaScript with all tests passing. (I say "almost" because it doesn't yet convert the file bin/hubot since it doesn't end in .coffee; see https://github.com/decaffeinate/bulk-decaffeinate/issues/90 .)

decaffeinate is working (meaning all files convert and all tests pass) on hubot as well as some other larger projects, so it seems to be pretty safe at this point (although not 100% bug-free):
https://github.com/decaffeinate/decaffeinate#status

Certainly there are some caveats, though, like various lint issues that can't be auto-fixed and a nuance involving constructors in JS classes. Given that this repo has been inactive, a big codebase change like this may not be worth it, but happy to provide any help or advice if you're interested in using decaffeinate!

**Comment by technicalpickles** [comment]
It has been awhile, but there is work to revitalize the hubot project, and porting to ES6 is now on the [roadmap](https://github.com/github/hubot/blob/master/ROADMAP.md)

**Comment by gasolin** [comment]
@technicalpickles good to see there's a roadmap to ES6!
Does the new ES6 hubot still need to back-compatible to node 0.10?

**Comment by bkeepers** [comment]
> Does the new ES6 hubot still need to back-compatible to node 0.10?

In general, I think we should support [LTS versions](https://github.com/nodejs/LTS#lts-schedule1) u that are still being maintained (currently 4 & 6), and the latest release (currently 7). So this would mean dropping 0.10 and 0.12 support since they're no longer maintained.

**Comment by rqc** [comment]
I guess that one important aspect is the backward compatibility of hubot scripts that have been written in `coffescript`. So, upon loading the scripts, the `coffeescript` compiler would still be called for those scripts that use it. Right?

**Comment by rqc** [comment]
Should [Coffeescript 2](http://coffeescript.org/v2/) be considered?

**Comment by bkeepers** [comment]
We'll get a proposal started soon that dives into the details of how the port to ES6 will work.

**Comment by gr2m** [comment]
The proposal is here: https://github.com/hubotio/evolution/issues/4
