### ISSUE TITLE
msg.envelope.room returns alphanumeric string and not the room name.

### ISSUE THREAD

**Issue by vikaskedia** [hubotio/hubot#1140]
my bot depends on the room name to take the action.

in the general room inside the coffeescript when i say:
room = msg.envelope.room
I get room = general

But for a user created room the same statement room = msg.envelope.room
gets room = GSbyy92x28zjuHaxz

Why is this happening ?

**Comment by pchaigno** [comment]
What do you call a *user created room*? Which adapter are you using?

**Comment by technicalpickles** [comment]
Some of it sounds like Slack (ie `general), but the room doesn't match up (`GSbyy92x28zjuHaxz`, where I'd expect `U1234`). Can you confirm @vikaskedia, or tell us the adapter otherwise?

This will probably be better filed on the adapter's repository. The main problem I suspect there will be that if this is changed, there could be hubots out there depending on this current behavior.

**Comment by jedipunkz** [comment]
same issue.

**Comment by mose** [comment]
It would help a lot to know which adapter you were using. Can you tell us?
