### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by JonathanRosado** [hubotio/hubot#1229]
Are there any plans of having an official Hubot docker image?

**Comment by mose** [comment]
I suspect it will come. In the while you can check #1271 there are some examples of existing Dockerfiles.

**Comment by technicalpickles** [comment]
As a user, what would you expect from a hubot docker image?

To me, the benefit of hubot is being super customized to your usage, so I am having a hard time thinking of a super generic image. It could be possible to make a base image (that is mostly just the nodejs environment) that knows how to run hubot in general, and you inherit from that to include your specific bot's dependencies and scripts.

**Comment by mose** [comment]
Yes I think that's what makes sense. Like a raw freshly made hubot-generator containerized and that can be customized or inherited.

**Comment by bkeepers** [comment]
One interesting scenario would be to publish each Hubot script with a Dockerfile declaring the services it depends on (and various parts of Hubot being broken into services where it makes sense). This isn't a 1:1 example, but @probot was designed to allow plugins to run stand-alone, or [grouped together in the same instance](https://github.com/probot/probot/blob/master/docs/deployment.md#combining-plugins).

I haven't fully through through how all this would work, so it might be nonsense.

**Comment by technicalpickles** [comment]
I haven't done much with docker, so maybe this is naive, but this is what I am thinking for docker support:

- base hubot image:
  - include node environment (ie inherit from an existing one)
  - know's how to launch hubot, ie `bin/hubot`
- templated 
  - npm install's local package.json to get dependencies (either for script packages or local script's dependencies) 
  - includes the `scripts` (and other?)  in the working directory

**Comment by rqc** [comment]
There is also the issue of where to host the `Dockerfile`. There are typically two strategies:

1. Within the project's source code (at the root of the project). In this case, the `docker build` would use the current project as the context for the image.
2. In a separate repo. In this case, the `Dockerfile` would need to download specific releases depending on the image tag to have a one-to-one match with the github release versions (git tags) and the docker images.

Option `1.` is typically the easiest to setup and maintain, however, there are some use cases where you would need `2.`.

**Comment by technicalpickles** [comment]
@rqc thanks for the info!

> however, there are some use cases where you would need 2..

Can you think of any general cases for that? Or specific projects that have needed to do it that way?

**Comment by rqc** [comment]
@technicalpickles I have seen this mostly on repositories for _official_ docker images. These are docker images for projects that have been somewhat curated or gone through a special process between the project owners and Docker, Inc. Here are some examples:
* [docker images for node](https://github.com/nodejs/docker-node/tree/581eebd097343c9f1c1ceb5260cd2ec770410e29)
* [redis](https://github.com/docker-library/redis/tree/24aa66d88990e0eeec71bd39862744fdb7b862e4)

One particularity, is that instead of using git tags to _version_ the images, the Dockerfiles are namespaced in folders (e.g. `v3.0/Dockerfile`). 

I've also seen this used mostly in projects in which the build process yields a binary executable (e.g. `*.jar`, `*.war`, etc) and the source code is not necessary to run the program. This is not the case with `hubot` since we need the source code to be included in the docker image.

**Comment by technicalpickles** [comment]
I learned some docker things 😅  However, I am still thinking about this:

> To me, the benefit of hubot is being super customized to your usage, so I am having a hard time thinking of a super generic image. It could be possible to make a base image (that is mostly just the nodejs environment) that knows how to run hubot in general, and you inherit from that to include your specific bot's dependencies and scripts.


On docker hub, there are a few hubot images, which generate a bot (via `yo`) as part of their processing:

- https://hub.docker.com/r/rplan/hubot/
- https://hub.docker.com/r/rewardle/hubot/
- https://hub.docker.com/r/cataska/hubot-slack/

With these, you could plausibly mount a volume to the `scripts` directory to have user-defined scripts. You would not be able to install dependencies for them though.

Plausibly you could inherit from these images to populate the scripts yourself, and have a package.json specifically for them that is npm installed as part of image building. That starts to seem a little weird from a node-load-path perspective, but might be doable. That also wouldn't account for script packages though.

Maybe an inheriting image could just replace the package.json with their own, and re-install? Would that take away some of the usefulness of a hubot image?

Also for reference, I made a Dockerfile for a recently created hubot, and it was super straightforward:

```
FROM node:4.8.4

WORKDIR /app

COPY package.json package.json
RUN npm install

COPY . .

EXPOSE 8080
CMD ["npm", "start", "-s"]
```

**Comment by rqc** [comment]
@technicalpickles 

-`COPY . .` will copy the `package.json` as well, so the `COPY package.json package.json` might be redundant.
- Docker `build` will create a new image layer for each statement in the `Dockerfile` and this adds to the size of the image. So, it is important to consolidate statements as much as possible. 
- Clean the `npm` cache after running `npm install` in the same `RUN` statement. 
- Add a `.dockerignore` file which follows the same conventions as a `gitignore` to reduce the context that is sent to the docker API during build.
- I would recommend using `alpine` based images which are smaller than `debian` based images. 

I would also consider the use case of extending an image from the base hubot image that will point hubot to read from a local integration using `HUBOT_SCRIPTS` env var. This is useful for integrations that are not open source and not published through github/ npm.org.

**Comment by technicalpickles** [comment]
> COPY . . will copy the package.json as well, so the COPY package.json package.json might be redundant.
> Docker build will create a new image layer for each statement in the Dockerfile and this adds to the size of the image. So, it is important to consolidate statements as much as possible.

The reason for splitting out package.json is to build the layer that requires a potentially slower `npm install` (plus a cache clear as you suggested) separate from copying everything else. If you are actively developing a bot, you wouldn't want every change to a script to cause this part to be rebuilt.

> Clean the npm cache after running npm install in the same RUN statement.

That makes sense, and I've seen that pattern. I just threw this one together in like 20 minutes 😅 

> I would recommend using alpine based images which are smaller than debian based images.

It seems that most docker images have both a debian-based and an alpine based image. I think there's value in still having a debian based image, because most instructions you see for getting packages running are more likely to have debian-based instructions than alpine ones.
