### ISSUE TITLE
Hubot for Microsoft Teams

### ISSUE THREAD

**Issue by AzCii** [hubotio/hubot#1260]
Have anyone looked at creating a Hubot adapter for Microsoft Teams (teams.microsoft.com)?

**Comment by tvvignesh** [comment]
Looking forward to this. It will be better if Hubot can integrate with Microsoft Bot Framework (which may support teams) in someway so that if they add/remove support, it can work well with Hubot.

**Comment by jvarness** [comment]
I've been trying to get some code working, but the bot I made for my company has some proprietary stuff I don't want out in public domain. That and I need a cloud endpoint that the bot can be reached from.

My idea is to use the Microsoft Node.js SDK to create a UniversalBot and setup events in the hubot adapter. As soon as I can get a proper test bed going to make sure it works I have no problem releasing it to the public.

**Comment by ojacques** [comment]
The new [custom bot](https://msdn.microsoft.com/en-us/microsoft-teams/custombot) capability in MS teams is heading there. From the look of it, one could now create an Hubot adapter for MS teams. 
There is a [sample custom bot](https://github.com/OfficeDev/microsoft-teams-sample-custombot) in C# on Github. I haven't look at the code yet.

**Comment by israelshirk** [comment]
According to https://microsoftteams.uservoice.com/forums/555103-public-preview/suggestions/16937848-allow-adding-bots-to-channels this has been completed on Microsoft's side; however I have not verified.

**Comment by calebmeyer** [comment]
@israelshirk I can verify that you can add bots to channels. Unfortunately, unless you @mention them specifically, they're not allowed to "listen" to the channel. This removes most of the utility of a bot (it makes it a special case of a slash command).

To fix this issue, please vote here: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/18646171-remove-bot-mention-requirement

**Comment by israelshirk** [comment]
Thanks @calebmeyer!

**Comment by markottaviani** [comment]
Looks like Microsoft has posted a Bot Framework Hubot adapter:  https://github.com/Microsoft/BotFramework-Hubot

**Comment by wumingzhang** [comment]
Have anyone manage to actually get their hubot connected with ms teams?

**Comment by israelshirk** [comment]
@wumingzhang Yes, works great

**Comment by ojacques** [comment]
It looks like with botFramework, hubot needs to be hosted on the public internet per this issue on botframework adapter for Hubot: @Microsoft/BotFramework-Hubot#15.
The issue with that is that it will require some sort of reverse proxy or VPN to reach infrastructure which is only on the intranet. 
In the issue above, there is a mention about [Orky](https://github.com/OfficeDev/Orky), which looks like some sort of a botframework proxy, to which Hubot connects thanks to an Hubot adapter. 

Hubot (on prem) w/orky adapter ----> Orky bot (internet) <----> MS Teams

**Comment by israelshirk** [comment]
I got a question off list about this, which I'm going to answer on-list for posterity.

## First, get hubot online
You'll want to have it booted up with BotFramework-Hubot and non-functioning credentials, but the right port.  We'll add credentials later.  Sounds weird, I know, but it'll work out in the end.  Just trust me.  You'll want port _3976_ open to the interweb (or at least to Azure's cloud netmasks) so that Microsoft's REST API calls from Teams -> BotFramework -> _your botframework implementation_ -> _hubot_ make it through.

## Botframework.com
So, first you're going to want to register yourself at https://dev.botframework.com/.  This is the integration point.

* There's a step through the M$ registration, and then you're logged into dev.botframework.com with a header menu that has an option of _My Bots_.
* Click it.
* Hit Create and do _register an existing bot_.
* Fill in the next form really good-like.  At _messaging endpoint_ enter the endpoint you created above!
* Now we'll create the Microsoft App ID and Password that the local Bot Framework wants.  Just follow the buttons and you'll be good to go.
* Paste in your App ID into the Bot Framework form because Microsoft's left hand doesn't talk to its right.
* Add any other owners you'd like to have in case you get a cold and don't want to be on call.

Agree, and you're well on your way.  Make sure you have microsoft teams selected as your chat framework (BotFramework is an aggregator service - so failing to select Microsoft Teams and the proper channels here can be painful).

## Credential Hubot and restart
Pretty straightforwards.

## Test
You can test hubot first from the dev.botframework.com dashboard.  Any connectivity issues between BotFramework's APIs and your hubot can be sussed out by using that integration.  As long as that is working with your hubot, your problem is then between your BotFramework configuration and your Microsoft Teams configuration.  Which can be a hassle, but typically starting from scratch it's fairly straightforwards.  Just make sure you're logged in with the right organization, account, privileges, and you should just end up in the right place from the beginning.

If you have any questions I'm a little time limited, but I'll help where I can on here or every once in a while I'm on the hubot slack.  Hope this helps!

**Comment by mose** [comment]
Great input @israelshirk thanks! :+1:

**Comment by wumingzhang** [comment]
the messaging endpoint require to be https, i guess you need do some haproxy between?

**Comment by israelshirk** [comment]
Correct; my apologies.  I used nginx.

**Comment by wumingzhang** [comment]
thanks @israelshirk , still missing the last piece of the puzzle. I got it working in "test" mode in dev.botframework.com, but cannot connect properly into teams. anything special need to be done?

**Comment by toomuchio** [comment]
@israelshirk How did you configure the end-point? I have hubot running but when I do

```curl -i https://127.0.0.1:3976
curl: (7) Failed to connect to 127.0.0.1 port 3976: Connection refused
```
I get nothing?

**Comment by toomuchio** [comment]
Just in case anybody else gets stuck on this it's.

Port 8080 not 3976, you can reverse proxy it with Nginx to expose it publicly.
If you want to keep to hubot spec you should alter BOTBUILDER_ENDPOINT to be /hubot/api/messages as well.
curl -X POST -H "Content-Type: application/json" -d '{"test":"test"}' localhost:8080/api/messages
