### ISSUE TITLE
Increasing hubot process memory

### ISSUE THREAD

**Issue by ravikiranj** [hubotio/hubot#1354]
Hi there,
    Is there any way I can increase the hubot process memory ? I have been consistently seeing GCs recently. Our instance supports 2k+ users and has a good amount of redis brain data.

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

<--- Last few GCs --->

513860770 ms: Scavenge 1397.8 (1459.0) -> 1397.8 (1459.0) MB, 0.8 / 0 ms (+ 2.7 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
513861989 ms: Mark-sweep 1397.8 (1459.0) -> 1372.8 (1457.7) MB, 1219.9 / 0 ms (+ 3.4 ms in 2 steps since start of marking, biggest step 2.7 ms) [last resort gc].
513863309 ms: Mark-sweep 1372.8 (1457.7) -> 1372.8 (1457.7) MB, 1319.6 / 0 ms [last resort gc].
```

**Comment by technicalpickles** [comment]
I have not seen this personally, but I did some very brief ~googling~ researching on how to increase node memory in general. I found [this article](http://prestonparry.com/articles/IncreaseNodeJSMemorySize/):

> Just use the --max_old_space_size=<size> command.

How to apply this will depend on how you run hubot. If you include the `bin/hubot` command that came with the original generator, it's calling node_modules/.bin/hubot, which is a coffeescript file with a `#!/usr/bin/env coffee` shebang.

The `coffee` has a `--nodejs` option for passing arguments to nodejs, so that could be updated with --max_old_space_size. The problem with that would be it'd be replaced if npm ever updated/re-installed the package.

You could call `coffee` with the arguments directly on `node_modules/.bin/hubot` to pass in the arguments you need. Just keep in mind that hubot itself was ported to javascript, so you might get an unobvious syntax error after upgrading past 3.0.

**Comment by ravikiranj** [comment]
Thank you very much for the pointers @technicalpickles!
