### ISSUE TITLE
hubot debbugging

### ISSUE THREAD

**Issue by akki005** [hubotio/hubot#1373]
I am unable to debug hubot scripts. I am using node-inspector for it.

i started node-inspector  using "node-inspector --no-preload --web-port=8001"
and when i ran "coffee --nodejs --debug node_modules/.bin/hubot" in another command window  it shows below error :

(node:9764) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
Debugger listening on [::]:5858
node_modules/.bin/hubot:4:1: error: reserved word "case"
case `uname` in
^

please need some help

**Comment by timkinnane** [comment]
The first line re `DeprecationWarning` you can ignore. (I think) It's because hubot's javascript es2015 code is compiled by babel to be compatible with node v4 and you might be on node v6 so some of the methods are depreciated, but still supported.

Which version are you running? In v3 most coffeescript has been converted to es6, apart from that main file, for compatibility. So there's probably more effective ways to run hubot for debugging that don't require it to pass through a coffeescript compiler. I'm not up to date with that though, it's changed quite a bit lately. I can't find `case uname in` anywhere in the current codebase, but happy to help if you point me at the release you're on.
