### ISSUE TITLE
package.json version

### ISSUE THREAD

**Issue by kemosabe73** [hubotio/hubot#1389]
The version at package.json is at 0.0.0-development yet the latest released version is v3.0.1, shouldn't they be the same?

**Comment by timkinnane** [comment]
Hubot uses `semantic-release` to publish new versions automatically when builds pass CI. So the package version is never manually updated. It's a bit confusing for sure, but that is how it's intended. See [semantic-release](https://github.com/semantic-release/semantic-release) for more info, it's a great package.

**Comment by kemosabe73** [comment]
Thank you for replying. 

I read the  link you provided and under the **How Does It Work** section, there is a table which indicates what happens in the series, and under **2 . semantic release pre** it is written:

"Based on all commits that happened since the last release, _**the new version number gets written to the package.json**_ "

Doesn't that mean the version number should be updated automatically by semantic-release?

**Comment by timkinnane** [comment]
I think those docs are either out of date, or just confusing, because they also contain this...

> Why is the package.json’s version not updated in my repository?

https://github.com/semantic-release/semantic-release#why-is-the-packagejsons-version-not-updated-in-my-repository

Then there's this issue discussing possible options and work-arounds...

https://github.com/semantic-release/semantic-release/issues/211

I think the problem is that it would require an extra commit to patch the package.json after every build, which might pollute the history and cause other problems.

Truthfully, I found it quite challenging to get working with my projects, but once I did it mostly took care of itself and has been helpful.
