### ISSUE TITLE
Hubot Error: Script is using deprecated documentation syntax

### ISSUE THREAD

**Issue by huiminzeng** [hubotio/hubot#1448]
Hello Team! I am using docker compose to deploy Hubot.  But I got an error when i tried to use my own scripts.
Please have a look at this link. There are some screenshots there.
https://github.com/RocketChat/hubot-rocketchat/issues/292

Any suggestions would be greatly appreciated.
Thanks!

**Comment by andreasolund** [comment]
@huiminzeng You're just missing the documentation comments at the top of your `test.coffee` file, they are used to parse information about your commands to the `hubot help` command. You can see an example here: https://github.com/hubot-scripts/hubot-shipit/blob/master/src/shipit.coffee. The second printout can be fixed by removing `hubot-scripts.json`.

**Comment by huiminzeng** [comment]
@andreasolund  thank you so much!
