### ISSUE TITLE
Coffeescript 2?

### ISSUE THREAD

**Issue by blitmap** [hubotio/hubot#1452]
Hi,

I in no way want to create a counter-productive conversation.

I saw that Hubot relatively recently converted to Javascript from Coffeescript.  For a while it was uncertain if Coffeescript would support transpiling to ES2015 Javascript.  When I looked through the issues raised it seemed related to how Coffeescript did import/require().  Now there is officially a Coffeescript 2 that supports ES2015 classes.

I don't know what I'm suggesting, but had this been looked at?

https://coffeescript.org/#classes

Feel free to tell me this has been settled and I'll bugger off. :)

**Comment by technicalpickles** [comment]
That is good to know about coffeescript 2, thanks!

I don't see us switching back to coffeescript now that we have moved over though. The main motiviations in my mind are:

- using javascript means it's more approacable to existing javascript developers than coffeescript is
- it is simpler for letting users use their own coffee-script version, rather than being tied to hubot's required version.
