### ISSUE TITLE
Hubot behind a proxy

### ISSUE THREAD

**Issue by samstarling** [hubotio/hubot#287]
I'm behind a proxy, and while `hubot ping` works just fine, `math me 2+2` doesn't work. In fact, any step that uses a `get()` in the script just doesn't work at all. How do I either:
1. Tell Hubot to use a proxy when doing a `.get()`?
2. Get some additional debugging out of Hubot so that I can diagnose why things aren't working?

Thanks!

**Comment by nottinhill** [comment]
+1 for this feature if you guys implement it

**Comment by MitchK** [comment]
Hey all,
I've created a gist with a quick fix, we use it for our company's hubot. I know your feels, corporate proxies are awesome for system administrators, but suck for developers.

https://gist.github.com/MitchK/69fbfb90fce6e76afd62

Please note that all requests will go through that proxy, even requests internally. Depending on the corporate proxy configuration, this might result in 404 requests if requesting internal sites through that proxy.

Since we use Docker to deploy our hubot(s), we just simply overwrite this file after any ```npm install``` or ```yo hubot```:
```
...
# Run yeoman
RUN su $HUBOT_USER -c "yo hubot --owner=\"$HUBOT_OWNER\" --name=\"$HUBOT_NAME\" --description=\"$HUBOT_DESCRIPTION\" --adapter=\"$HUBOT_ADAPTER\" --defaults"

# Add proxy hack for hubot
ADD hacks/node_modules/hubot/node_modules/scoped-http-client/src/index.js node_modules/hubot/node_modules/scoped-http-client/src/index.js
...
```

Hope that helps some people locked behind firewalls. Cheers

**Comment by technicalpickles** [comment]
For those following along, @michaelansel started work on a solution to this over in https://github.com/github/hubot/issues/884 and https://github.com/technoweenie/node-scoped-http-client/issues/31

**Comment by jlbates504** [comment]
@michaelansel Where is it you load in your proxy work around?

**Comment by michaelansel** [comment]
@jlbates504 You just create a script with no listeners. It will get executed during startup and be ready for all your listeners to use afterwards.

https://hubot.github.com/docs/patterns/#forwarding-all-http-requests-through-a-proxy

**Comment by notok** [comment]
Hi all,

I wrote an external script that loads proxy setting from environment variables
to make it easier. I hope this helps.

https://www.npmjs.com/package/hubot-proxy-loader

**Comment by paschmann** [comment]
@notok - thanks, this worked like a champ :+1:
