### ISSUE TITLE
IRC Robot says everything twice

### ISSUE THREAD

**Issue by dcarley** [hubotio/hubot#71]
Hubot seems so keen to talk to IRC that it repeats everything twice.

```
09:44 <@dan> hubot: ping
09:44 < hubot> PONG
09:44 < hubot> PONG

From dan to #test: hubot: ping
undefined: PONG
27 Oct 09:44:47 - SEND: PRIVMSG #test :PONG
undefined: PONG
27 Oct 09:44:47 - SEND: PRIVMSG #test :PONG
```

**Comment by lukaszraczylo** [comment]
+1 on lost & re-established connection issue.

**Comment by michaelansel** [comment]
The double load on reconnect is likely caused by the 'connected' event getting emitted again. The robot listens for 'connected' and loads all scripts at that point (assuming it will only get fired once). This would be adapter dependent (adapter decides when to emit 'connected'). Can you confirm which adapter you are using when this happens?

**Comment by gmelika** [comment]
I use the hipchat adapter

**Comment by michaelansel** [comment]
Filed #919 to track the reconnecting issue

**Comment by brianjdoherty** [comment]
This was happening to me, and I realized I was running the hubot process twice on my server.  :-)
